### ISSUE TITLE
unable to add image to bottom and top dot view like triangle.

### ISSUE THREAD

**Issue by KarthikMandava** [amirdew/AMTooltip#6]
Could not load the "triangle-down" image referenced from a nib in the bundle with identifier "org.cocoapods.AMTooltip"

**Comment by amirdew** [comment]
make sure you run .xcworkspace not .xcodeproj,
try to clean and rebuild,
are you test Example? did it work for you?
I test it again with Xcode 9.1, there is not problem.

```
$ git clone https://github.com/amirdew/AMTooltip.git AMTooltipTest
$ open AMTooltipTest/Example/AMTooltip_Example.xcworkspace
```
